title: CIRCUIT 回路
logo: /assets/img/logo.png
description: Circuit(回路) is a blog a blog about DevOps culture and computational complexity.Think deeper, Build better.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: http://example.com/download.zip
  another_url: another value
  repository_url: https://github.com/grot666/grot666.github.io
collections:
  tech_posts:
    output: true