title: grot's blog
logo: /assets/img/pngwing.com.png
description: A MTG player ,a coder and a lover.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: http://example.com/download.zip
  another_url: another value
  repository_url: https://github.com/grot666/grot666.github.io
collections:
  tech_posts:
    output: true